### ISSUE TITLE
require('@magenta/music/node/transcription'); Does not work in serverside NodeJS

### ISSUE THREAD

**Issue by Mylab6** [magenta/magenta-js#414]
Hi all, I'm trying work off the Drumbot project and add a way to transcribe midi via an API endpoint. I'm getting stuck because the transcription module really wants a browser object. 

When trying to require transcription , 
const transcription = require('@magenta/music/node/transcription');

I get this error . 
```
\drumbot [master ≡ +2 ~2 -0 !]> yarn start
yarn run v1.15.2
warning ..\package.json: No license field
$ node server/app.js
\drumbot\node_modules\@magenta\music\node\transcription.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.mm=t():e.mm=t()}(global,(function(){return function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,fu

ReferenceError: window is not defined
    at Object.<anonymous> \drumbot\node_modules\@magenta\music\node\transcription.js:1:2307)
```

Then I attempted to add a window to the global context , with

`const Window = require('window');
global.window = new Window();`

The following error was returned 
```
`.\drumbot [master ≡ +2 ~2 -0 !]> yarn start
yarn run v1.15.2
warning ..\package.json: No license field
$ node server/app.js
Platform browser has already been set. Overwriting the platform with [object Object].
.\drumbot\node_modules\@magenta\music\node\transcription.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.mm=t():e.mm=t()}(global,(function(){return function(e){var t={};function n(r){if(t[r])return t[r].exports;var o=t[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,n),o.l=!0,o.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)n.d(r,o,fu

TypeError: s.OfflineAudioContext is not a constructor`
```

At this point I'm not sure what else I can do, is this designed to work serverside ? I've noticed the vast majority of the documentation is for client side code.

**Comment by notwaldorf** [comment]
Hmm, I think the problem here is that transcription (are you using onsets and frames?) uses the audio context to record and handle the audio, and that’s a browser spec, not a server side spec. I’m not sure what exactly you’re doing, but some googling led me to https://github.com/audiojs/web-audio-api, which is an implementation of the web audio API that should work in node.

**Comment by notwaldorf** [comment]
magenta.js was initially written as a browser library (so all client side), but we’ve recently made it work in node. However, this doesn’t means that all models will work in node — the ones that rely on browser features, such as the web audio api, won’t work out of the box, I’m afraid. I think only onsets and frames and gansynth are affected, and you might still get them to work with the library I linked!

**Comment by Mylab6** [comment]
Thanks for the fast response ! 

So I actually tried to use the web-audio api, 

`const Window = require('window');
global.window = new Window();
global.performance = Date;
global.fetch = require('node-fetch');
var AudioContext = require('web-audio-api').AudioContext
global.AudioContext = new AudioContext();
global.OfflineAudioContext = new AudioContext();

const mm = require('@magenta/music/node/music_vae');
const transcription = require('@magenta/music/node/transcription');

`

This still threw the `TypeError: s.OfflineAudioContext is not a constructor` error. 

This is what I ultimately want to do 
```
var fs = require('fs');
import { OnsetsAndFrames } from '@magenta/music'

export async function basicMidiGet() {

    const globalAny: any = global;
    global.performance = Date;
    global.fetch = require('node-fetch');
    var fs = require('fs');
    let fileName = 'hardCodedPathToFile.wav'
    let blob = fs.readFileSync(fileName)
    const model = new OnsetsAndFrames('https://storage.googleapis.com/magentadata/js/checkpoints/transcription/onsets_frames_uni');
    model.initialize().then(() => {
        model.transcribeFromAudioFile(blob).then((ns) => {
            console.log(ns)
            //fs.writeFileSync(__dirname + 'lab' )
        })
    })
}


```

At this point I might switch to the Python version ( yay for polyglots, even though I'm most comfortable in Node)   . I really want to create an API for generating midi from audio files. 

Thanks for your help! Feel free to keep this issue open if you eventually want to support this server side or close it if not .

**Comment by notwaldorf** [comment]
Ok so I think the problem is that the `transcribeFromAudioFile` method you want to call needs to use the audio context to go from a file blob to an audio buffer (code [here](https://github.com/tensorflow/magenta-js/blob/5940871ee9f38d3d9fd52f8e45b89f132353ca09/music/src/core/audio_utils.ts#L90). Instead of calling `transcribeFromAudioFile`, can you use the node web-api implementation to go from your audio file to an audio buffer, and then call `model.transcribeFromAudioBuffer(audio)` instead?

**Comment by Mylab6** [comment]
So I found a solution, 

I'm just using 

https://github.com/suchipi/test-it 
Which creates a simulated browser , allowing me to get this working. 

Thank you .

**Comment by notwaldorf** [comment]
Sounds good!

**Comment by martonszabolcs** [comment]
I tried the test-it but the magenta package doesn't work. Do you have any solution?

**Comment by notwaldorf** [comment]
I need to know a little bit more about how you're using it. For example, I said above that you need to not use `transcribeFromAudioFile`. Can you show me how you're using the model?

**Comment by martonszabolcs** [comment]
I just installed this package to my Node.Js server, and the very first time I just import the transcription `const model = require('@magenta/music/node/transcription');` and the response is: 
`ReferenceError: window is not defined`
My idea is that using this OnsetAndFrames model on mobile side (React Native), but I find a lots of dependency (Tone.js, Web-audio etc) what doesn't work in React Native.
So I made a Node.js server, and connection to the app. 
I'm thinking about it, how can I use this model with React Native
