### ISSUE TITLE
github pages broken

### ISSUE THREAD

**Issue by goldensunliu** [magenta/magenta-js#417]
can't find these links with our readme.mds:

- https://tensorflow.github.io/magenta-js/image/demos
- https://tensorflow.github.io/magenta-js/music

**Comment by notwaldorf** [comment]
Ahhh, good call. I just moved the repo to the magenta org and they're borked. They should be https://magenta.github.io/magenta-js/music/, https://tensorflow.github.io/magenta-js/image/demos, https://magenta.github.io/magenta-js/sketch/index.html etc.

I'll do a PR tomorrow, unless you want to send one!
