### ISSUE TITLE
API documentation links are broken

### ISSUE THREAD

**Issue by ggilder** [magenta/magenta-js#454]
Hi, not sure if this is the right place to file this, but on the [Magenta Getting Started page](https://magenta.tensorflow.org/get-started/) under JavaScript, the three "API docs" links are all broken, linking to pages like <https://tensorflow.github.io/magenta-js/music> that no longer exist.

The readme link for API docs goes to <https://magenta.github.io/magenta-js/music/> instead... however that page has "API docs" in the table of contents, but not anywhere on the page.

I haven't been able to find something that looks like real API docs... is it out there somewhere?

**Comment by adarob** [comment]
Thanks for reporting! You can follow the links on the right side of the main page of https://magenta.github.io/magenta-js/music/ to see the API docs.

**Comment by ggilder** [comment]
Gotcha... maybe I'm just not familiar with this doc format but that is very non-intuitive to me :)

**Comment by adarob** [comment]
Yes, well the main page there is just the README from the GitHub repo and is not specific to the API documentation. But I agree we should try to improve the linking while we're here.

**Comment by notwaldorf** [comment]
Links are now fixed on https://magenta.tensorflow.org/get-started!

**Comment by ggilder** [comment]
👏
