### ISSUE TITLE
dynamic link to the MusicVAE demo in the v1.16.0 documentation dead

### ISSUE THREAD

**Issue by ccjeff** [magenta/magenta-js#459]
gives a dynamic link not found error

**Comment by notwaldorf** [comment]
Which link? Like, on which page?

**Comment by ccjeff** [comment]
> Which link? Like, on which page?

I was trying to find the endless trios sample, the link is: https://goo.gl/magenta/endless-trios

Here is the error message: 

![image](https://user-images.githubusercontent.com/46590685/83639927-0301e500-a5de-11ea-9506-d397ff7dcd29.png)

Thx!

**Comment by adarob** [comment]
try goo.gl/magenta/endlesstrios
