### ISSUE TITLE
Cannot read property 'quantizationInfo' of undefined

### ISSUE THREAD

**Issue by Lightingooo** [magenta/magenta-js#478]
I just specify the quantizationInfo, but this errors still occur.

Unhandled Rejection (TypeError): Cannot read property 'quantizationInfo' of undefined
▶ 20 stack frames were collapsed.
(anonymous function)
C:/Users/lenovo/Desktop/Cam/src/services/magenta_manager.js:60
  57 |             console.log(samples);
  58 |             const rnnPlayer = new mm.Player();
  59 |             const qns = mm.sequences.quantizeNoteSequence(TWINKLE_TWINKLE, 4);
> 60 |             music_rnn.continueSequence(qns,20,1.2);
  61 |         });
  62 | 
  63 | }
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by notwaldorf** [comment]
Closing, as I couldn't repro and this issue is stale
