### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: ImageData is not defined

### ISSUE THREAD

**Issue by shadowpants18** [magenta/magenta-js#507]
Getting this warning whenever I try to use this repo for a discord bot, any ideas on why this is happening, and how I can fix it?

`const Canvas = require('canvas');
const discord = require('discord.js');
module.exports = {
    name:'mix',
    description:'merges two avatars of the mentioned users',
    async execute(msg, args, model){
        const canvas = Canvas.createCanvas(128,128);
        const ctx = canvas.getContext('2d');

        const canvas2 = Canvas.createCanvas(128, 128);
        const ctx2 = canvas2.getContext('2d');
        if(!msg.mentions.users){
            msg.channel.send('mention 2 users');
            return;
        }
        
        let tagged1 = msg.guild.member(msg.mentions.users.array()[0]);
        let tagged2 = msg.guild.member(msg.mentions.users.array()[1]);

        let image1 = tagged1.user.avatarURL({format : 'png'})
        let image2 = tagged2.user.avatarURL({format : 'png'})
        
        console.log('created images');

        let img1 = new Canvas.Image();
        let img2 = new Canvas.Image();

        img2.onload = () =>{
            img2.src = image2;
            ctx2.drawImage(img2, 0, 0, 128, 128);
        }
        img1.onload = () =>{
            img1.src = image1;
            ctx.drawImage(img1, 0, 0, 128, 128);
        }

        function stylize(){
            console.log('sup');
            model.stylize(canvas, canvas2).then((imageData) =>{
                console.log('done');
                ctx.putImageData(imageData, 0, 0);
            });
        }
        
        model.initialize().then(stylize);
        const attachment = new discord.MessageAttachment(canvas.toBuffer(), 'MixedImage.png');
        msg.channel.send(attachment);
    }
}
`

**Comment by notwaldorf** [comment]
It looks like you're using this in Node and not the browser, so I'm not super sure how that Canvas library work. Is the error in the `model.stylize(canvas, canvas2).then((imageData)` line? 

Looking at [the source code](https://github.com/magenta/magenta-js/blob/master/image/src/arbitrary_stylization/model.ts#L141), that function accepts either `HTMLElements` or an actual `ImageData` object, and there's a chance these `Canvas` objects are neither. Can you try passing the canvases' `ImageData` arrays to stylize instead?

**Comment by notwaldorf** [comment]
Closing this issue as stale because it has not had recent activity. If you have any more updates, please comment on this thread or open a new issue with more details. Thanks!
