### ISSUE TITLE
Dead Links at https://hello-magenta.glitch.me/

### ISSUE THREAD

**Issue by MikeParish** [magenta/magenta-js#510]
There appear to be dead links in the tutorial: https://hello-magenta.glitch.me/

They seem to link back to a repo that no longer exists: https://tensorflow.github.io

I hope this helps. Thanks!

## Under "Step 1: Making sounds with your browser"
NoteSequences: https://tensorflow.github.io/magenta-js/music/modules/_core_sequences_.html

## Under "Playing a NoteSequence"
Player: https://tensorflow.github.io/magenta-js/music/modules/_core_player_.html
SoundFontPlayer: https://tensorflow.github.io/magenta-js/music/classes/_core_player_.soundfontplayer.html

## Under "Visualizing a NoteSequence"
Visualizer: https://tensorflow.github.io/magenta-js/music/classes/_core_visualizer_.visualizer.html
configure: https://tensorflow.github.io/magenta-js/music/interfaces/_core_visualizer_.visualizerconfig.html

## Under "Useful Helpers"
(all links in this section)

## Under "Step 2: Using Machine Learning to make music"
(all links in this section except for Tensorflow.js)

## At the bottom of the page
(the documentation link)

**Comment by notwaldorf** [comment]
Yikes, thanks for catching that! Updated!
