### ISSUE TITLE
@magenta/music: `TypeError: Cannot read property 'hrtime' of undefined`

### ISSUE THREAD

**Issue by lhl2617** [magenta/magenta-js#514]
Hey! I recently resurrected an old `create-react-app` React project and bumped `@magenta/music` from 1.12.0 to 1.20.0 -- immediately upon startup I got `TypeError: Cannot read property 'hrtime' of undefined`

It seems to be related to #475 . It seems intended that local tests should use the node environment where `global.process` is defined, and for web builds the non-node versions are used. Likely, the environment detection resolved the running of the code to node, but the app preview is in the browser where node is not available.

I'm rolling back to a pre-#475 version--just FYI! I'm not sure if this is a `create-react-app` or magenta problem, I'll investigate further when I have time.

**Comment by lhl2617** [comment]
https://github.com/magenta/magenta-js/blob/e1f6a65088584e7f2257427cb92853580adf02f3/music/src/core/compat/global.ts#L27

```
const isNode = typeof global !== 'undefined';
```

Somehow this resolved to true in the environment..

**Comment by lhl2617** [comment]
It's my problem - closing this issue :)

Was doing
`import { NoteSequence } from '@magenta/music/node/protobuf/index';`
instead of
`import { NoteSequence } from '@magenta/music';`

**Comment by notwaldorf** [comment]
Whew! Glad it wasn't a real problem!
