### ISSUE TITLE
How to export audio_utils?

### ISSUE THREAD

**Issue by asterisk37n** [magenta/magenta-js#520]
## Question  
Is it possible to execute ```core/audio_utils.melSpectrogram``` in the browser (or mobile)?

## Background of question  
I develop mobile app with React Native and look for log melspectrogram function. For now, tensorflowjs provides ```tf.stft```, but doesn't mel scale converter. I look for a way to use  
```js
powerToDb(melSpectrogram(...))
```
from ```@magenta/music/core/audio_utils``` even if it's not well tested.

## What I did  
I forked and edited ```music/src/core/index.ts``` to import and export audio_utils.

```diff
+import * as audio_utils from './audio_utils';
 import * as aux_inputs from './aux_inputs';
 import * as chords from './chords';
 import * as constants from './constants';
 import * as sequences from './sequences';
 
 export {
+  audio_utils,
   aux_inputs,
   chords,
   constants,
```

, then ran ```npm run-scripts build```, and then replaced ```node_modules/@magenta/music/``` with ```magenta-js/music``` in my react-native application repository. It successfully built. But I couldn't import ```audio_utils``` as explained below.

```js
import {audio_utils} from '@magenta/music/node/core'
```
 fails with below error messages (It'll be fine because I don't run nodejs server). 
```
[Sun Nov 22 2020 09:35:48.101]  ERROR    TypeError: e.process.hrtime is not a function. (In 'e.process.hrtime()', 'e.process.hrtime' is undefined)
[Sun Nov 22 2020 09:35:48.101]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
[Sun Nov 22 2020 09:35:48.101]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```
Also, I tried to import es6 package, but
```js
import {audio_utils} from '@magenta/music/es6/core'
```
doesn't work throwing below error message. 

```
Module '"./node_modules/@magenta/music/es6/core"' has no exported member 'audio_utils'.ts(2305)
```

Was ```audio_utils``` not exported due to webpack build configuration? Are there node specific dependency and ```audio_utils``` can't be run on frontend? or did I make a stupid mistake when importing package?

## Related
https://github.com/magenta/magenta-js/issues/393
https://github.com/magenta/magenta-js/pull/405

**Comment by notwaldorf** [comment]
I'll paste here the answer from #393, which I think answers this question:

```
Alright, I've thought about this more and I don't think we want to add all these audio_utils as a public 
API -- we added them for a model in particular, and the problem is that they aren't tested for all cases. 
We definitely don't plan on working on them or adding new features, and there's many libraries out 
there that give you different ways to do stfts. So this is why I think they should remain a private API.```

Is there something in particular you need from audio_utils? I recommend maybe just copying that into a local function that you can use.

**Comment by notwaldorf** [comment]
Closing, as I don't think this is something that we want to magenta.js at this point.
