### ISSUE TITLE
Parsing from serialized string

### ISSUE THREAD

**Issue by axhue** [magenta/magenta-js#523]
Hi!

does anyone know how to read a serialized string into magentaJS player/notesequence? I'm running my model on a server and sending the result (as a string) to be read and played on the client.

I'm thinking of converting string -> midi -> back into note sequence but i'd like to use it as a last resort.

Thanks :D

**Comment by notwaldorf** [comment]
If I understand your question correctly, the serialized string is just a normal serialized JSON object. So assuming you have some NoteSequence `ns`, 
- this is how you get it into a string: `const str = JSON.stringify(ns)`
- this is how you parse that string back into a NoteSequence: `const ns2 = JSON.parse(str)`

**Comment by axhue** [comment]
Thanks for your response. I actually just figured it out! Turns out ajax doesnt handle octet-stream automatically. I tweaked it to accept a binary array which was casted to Uint8Array on the client side and decoded using protobuf.

Thanks again! and awesome work you guys are doing :smiley:

**Comment by notwaldorf** [comment]
Sweet! Glad you got it!
