### ISSUE TITLE
[ddsp] make my own model

### ISSUE THREAD

**Issue by hihunjin** [magenta/magenta-js#560]
@EdwinToh @notwaldorf 
Hi. I'd like to put my own instrument on [ddsp](https://github.com/magenta/magenta-js/blob/master/music/demos/ddsp_tone_transfer.ts#L111). Would you please tell me how to make my own ``model.json`` and weight/checkpoint files? Thanks in advance.

**Comment by notwaldorf** [comment]
Cc @jesseengel do you know the answer to this?

**Comment by hihunjin** [comment]
Thanks for the reply.
I made it by myself. But, Is it possible to upload my weights on the googleapi storage of yours? like [this](https://storage.googleapis.com/magentadata/js/checkpoints/ddsp/violin/model.json)

**Comment by notwaldorf** [comment]
Ah unfortunately that storage bucket is just for the checkpoints maintained by the team, but you can create your own buckets: https://cloud.google.com/storage/docs/creating-buckets

Otherwise, putting the checkpoints in any cloud folder/publically available location should work as well.
