### ISSUE TITLE
Add mt3 to checkpoints usable?

### ISSUE THREAD

**Issue by rhelsing** [magenta/magenta-js#626]
Would it be possible to add the transcription checkpoint? Would it work with the OnsetsAndFrames model? I was hoping it would be reference-able like so:

```js
model = new mm.OnsetsAndFrames('https://storage.googleapis.com/magentadata/js/checkpoints/transcription/mt3');
```

https://colab.research.google.com/github/magenta/mt3/blob/main/mt3/colab/music_transcription_with_transformers.ipynb

**Comment by cghawthorne** [comment]
Unfortunately no. The architecture differences between the two models are substantial, and we don't have a javascript implementation for MT3. One big difficulty would be getting a Transformer implementation that is performant enough in javascript. We're exploring ways to make the model easier/faster to use, but for now, I recommend just using the colab notebook.

**Comment by rhelsing** [comment]
@cghawthorne thanks for getting back to me!

**Comment by rhelsing** [comment]
@cghawthorne Would you be able to point me to the best resource for getting the model up and running on a local machine in python? as opposed to a collab notebook.

**Comment by cghawthorne** [comment]
The code for running locally will be basically the same as what's in the colab notebook. So I'd start by copy/pasting the colab notebook into a local python file.
